production: &production
  facebook:
    key: 182798436442915
    secret: 824acc7b16e857957d38f81c8bc7c471
  # twitter:
  #   key: xxxxxxxxxxx
  #   secret: XXXXXXXXXXXXXXXXXXXXXXXXX

development: &development
  <<: *production
  facebook:
    key: xxxxxxxxxxx
    secret: XXXXXXXXXXXXXXXXXXXXXXXXX

test:
  <<: *development
